version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
