version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
  redis:
    image: redis:6.2.1-alpine
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A RocketDataProject worker -B -E -l INFO
    env_file:
       - .env
    depends_on:
      - redis
      - web
    volumes:
      - ./:/app/