# Generated by Django 3.2.4 on 2021-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE')], default=1, max_length=12),
        ),
    ]
