# Generated by Django 3.2.4 on 2021-06-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210615_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_amount_wages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
